name: Generate snake
on:
  schedule:
    - cron: "0 0 * * *"   # todos los d√≠as 00:00 UTC
  workflow_dispatch:       # te deja ejecutarlo a mano

permissions:
  contents: write          # necesario para commitear el SVG

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure output dir
        run: mkdir -p output

      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: matire4
          outputs: |
            output/snake-dark.svg?palette=github-dark&color_snake=#22c55e
            output/snake-light.svg?palette=github&color_snake=#0ea5e9
            output/snake-ocean.gif?color_snake=#22c55e&color_dots=#d1fae5,#a7f3d0,#6ee7b7,#34d399,#10b981

      - name: Commit snake.svg
        uses: EndBug/add-and-commit@v9
        with:
          add: "output/snake.svg"
          message: "chore: update snake"
